
inputs:
  context:
    type: string
    required: true
  context-filter:
    type: string
    default: .
  items:
    type: string
    required: true
  name:
    type: string
    default:
  secret:
    type: string
    required: true
  steps:
    type: string
    required: true

outputs:
  out:
    value: ${{ steps.steps.outputs.steps }}

runs:
  using: composite
  steps:
  - uses: envoyproxy/toolshed/gh-actions/jq@bc3a1413c467db0ef869a5b5adc7376379a558fb
    name: Context
    id: context
    with:
      input: ${{ inputs.context || '{}' }}
      filter: |
        ${{ inputs.context-filter }}
        | . * {"items": ${{ inputs.items }}}
  - uses: envoyproxy/toolshed/gh-actions/jq@bc3a1413c467db0ef869a5b5adc7376379a558fb
    name: Steps (JSON)
    id: steps-json
    with:
      input: ${{ inputs.steps }}
      input-format: yaml
  - uses: envoyproxy/toolshed/gh-actions/jq@bc3a1413c467db0ef869a5b5adc7376379a558fb
    name: Steps
    id: steps-subs
    with:
      input: ${{ steps.steps-json.outputs.value }}
      print-result: ${{ fromJSON(env.CI_DEBUG || false) || fromJSON(env.RUNNER_DEBUG || false) }}
      filter: |
        . as $steps
        | ${{ steps.context.outputs.value }}
        | .items as $items
        | [] as $out
        | $items
        | to_entries
        | map(.key as $k | $out | . + [($steps | walk(if type == "string" then sub("\\$KEY"; "\($k)") else . end))])
        | flatten

  - uses: envoyproxy/toolshed/gh-actions/using/steps@bc3a1413c467db0ef869a5b5adc7376379a558fb
    id: steps
    with:
      name: ${{ inputs.name }}
      steps: ${{ steps.steps-subs.outputs.value }}
      context: ${{ steps.context.outputs.value }}
      secret: ${{ inputs.secret }}
      step-format: json
