
inputs:
  id:
    type: string
    required: true
  data:
    type: string
    required: true
  repository:
    type: string
  app-id:
    type: string
  app-key:
    type: string
  token:
    type: string
    default:


outputs:
  checks:
    value: ${{ steps.checks.outputs.value }}

runs:
  using: composite
  steps:
  - uses: envoyproxy/toolshed/gh-actions/appauth@5ff99e250807ec3b28f1adc1abeb04e283bed25d
    name: App auth
    id: appauth
    if: ${{ inputs.app-id && inputs.app-key }}
    with:
      key: '${{ inputs.app-key }}'
      app_id: ${{ inputs.app-id }}
  - name: Progress status check
    id: progress
    run: |
      response=$(echo $INPUT | gh api -XPATCH --input - repos/${{ inputs.repository || github.repository }}/check-runs/${{ inputs.id }})
      echo "response=${response}" >> $GITHUB_OUTPUT
    shell: bash
    env:
      INPUT: ${{ inputs.data }}
      GH_TOKEN: ${{ inputs.token || steps.appauth.outputs.token }}
  - uses: envoyproxy/toolshed/gh-actions/jq@5ff99e250807ec3b28f1adc1abeb04e283bed25d
    name: Print check response
    with:
      input: ${{ steps.progress.outputs.response }}
      options: -C
      print-result: true
