
inputs:
  uses:
    type: string
    required: true
  with:
    type: string
    default:

runs:
  using: composite
  steps:
  # .tmp.action/action.yml **must** be hardcoded

  - uses: envoyproxy/toolshed/gh-actions/jq@f9e295520598df1e185de8f85a2bb8c1b252aa7b
    id: yaml
    with:
      input: ${{ inputs.with }}
      input-format: yaml

  - run: |
      mkdir -p .tmp.action
      cat << EOF > .tmp.action/action.yml
      runs:
        using: composite
        steps:
        - name: Run (${{ inputs.uses }})
          id: run
          uses: ${{ inputs.uses }}
          with: ${{ steps.yaml.outputs.json || '{}' }}
      EOF
    shell: bash
  - name: Run (.tmp.action)
    uses: ./.tmp.action
  - name: Cleanup (.tmp.action)
    if: always()
    shell: bash
    run: rm -rf .tmp.action
