
inputs:
  uses:
    type: string
    required: true
  with:
    type: string
    default:

runs:
  using: composite
  steps:
  # .tmp.action/action.yml **must** be hardcoded

  - uses: envoyproxy/toolshed/gh-actions/jq@63db4aae4774b334ec8a686b6a12848e526798de
    id: yaml
    with:
      input: ${{ inputs.with }}
      input-format: yaml

  - run: |
      mkdir -p .tmp.action
      cat << EOF > .tmp.action/action.yml
      runs:
        using: composite
        steps:
        - name: Run (${{ inputs.uses }})
          id: run
          uses: ${{ inputs.uses }}
          with: ${{ steps.yaml.outputs.json || '{}' }}
      EOF
    shell: bash
  - name: Run (.tmp.action)
    uses: ./.tmp.action
  - name: Cleanup (.tmp.action)
    if: always()
    shell: bash
    run: rm -rf .tmp.action
