
inputs:
  url:
    type: string
    required: true
  variant:
    type: string
    required: true
  image:
    type: string
    default: envoyproxy/envoy


runs:
  using: "composite"
  steps:
  - uses: envoyproxy/toolshed/gh-actions/fetch@474c797b657a4bd69c31276de7c8052c53b81d4d
    id: fetch
    with:
      url: ${{ inputs.url }}
  - run: |
      echo "Copy oci image: oci-archive:${{ steps.fetch.outputs.path }} docker-daemon:${{ inputs.image }}:${{ inputs.variant }}"
      skopeo copy -q "oci-archive:${{ steps.fetch.outputs.path }}" "docker-daemon:${{ inputs.image }}:${{ inputs.variant }}"
      rm ${{ steps.fetch.outputs.path }}
    shell: bash
