# TODO: fold this into jq action

inputs:
  input:
    type: string
    required: true
  filter:
    type: string
    default: .

outputs:
  exit-code:
    value: ${{ steps.command.outputs.actual }}
  command:
    value: ${{ steps.command.outputs.value }}
  output:
    value: ${{ steps.output.outputs.output }}


runs:
  using: composite
  steps:
  - uses: envoyproxy/toolshed/gh-actions/jq@06af387ebf41196762cf6885875c24b0ba2f687b
    id: command
    with:
      input: ${{ inputs.input }}
      input-format: yaml
      print-output: ${{ fromJSON(env.CI_DEBUG || 'false') && true || false }}
      options: -r
      filter: ${{ inputs.filter }}
  - id: output
    run: |
      ${{ steps.command.outputs.value }}
    shell: bash
