inputs:
  images:
    type: string
    required: true
  env_prefix:
    type: string
    default: OUTPUT

outputs:
  shas:
    value: ${{ steps.images.outputs.value }}


runs:
  using: composite
  steps:
  - uses: envoyproxy/toolshed/gh-actions/jq@b7a1b501cdfaa62c13b69a48a23ea4fc77c0537a
    id: yaml
    with:
      input: ${{ inputs.images }}
      input-format: yaml
  - uses: envoyproxy/toolshed/gh-actions/foreach@b7a1b501cdfaa62c13b69a48a23ea4fc77c0537a
    id: json_actions
    with:
      items: ${{ steps.yaml.outputs.value }}
      steps: |
        - uses: envoyproxy/toolshed/gh-actions/docker/sha@b7a1b501cdfaa62c13b69a48a23ea4fc77c0537a
          id: $KEY
          with:
            image: >-
              %{{ fromJSON(inputs.context).items['$KEY'] }}
            env_var: ${{ inputs.env_prefix }}_$KEY

  - uses: envoyproxy/toolshed/gh-actions/jq@b7a1b501cdfaa62c13b69a48a23ea4fc77c0537a
    id: images
    with:
      input: ${{ steps.json_actions.outputs.out }}
      filter: |
        .
        | fromjson
        | with_entries({key: .key, value: .value.outputs.sha})
