inputs:
  images:
    type: string
    required: true
  env_prefix:
    type: string
    default: OUTPUT
outputs:
  shas:
    value: ${{ steps.images.outputs.shas }}

runs:
  using: composite
  steps:
  - uses: envoyproxy/toolshed/gh-actions/jq@5ff99e250807ec3b28f1adc1abeb04e283bed25d
    id: yaml
    with:
      input: ${{ inputs.images }}
      input-format: yaml
  - uses: envoyproxy/toolshed/gh-actions/jq@5ff99e250807ec3b28f1adc1abeb04e283bed25d
    id: json_actions
    with:
      input: ${{ steps.yaml.outputs.json }}
      filter: |
        {runs: {using: "composite", steps: [to_entries[] | {
          uses: "envoyproxy/toolshed/gh-actions/docker/sha@5ff99e250807ec3b28f1adc1abeb04e283bed25d",
          id: .key,
          with: {
            image: .value,
            env_var: "${{ inputs.env_prefix }}_\(.key)",
        }}]}}
  - run: |
      mkdir -p .tmp.action
      echo '${{ steps.json_actions.outputs.value }}' > .tmp.action/action.yml
    shell: bash
  - name: Run (.tmp.action)
    uses: ./.tmp.action
  - name: Cleanup (.tmp.action)
    if: always()
    shell: bash
    run: rm -rf .tmp.action
