
inputs:
  name:
    type: string
    default: env
  env:
    type: string
    required: true
  env-format:
    type: string
  env-filter:
    type: string


runs:
  using: composite
  steps:
  - uses: envoyproxy/toolshed/gh-actions/jq@dd0c20b6f9fd7edef45a0cd05016eaef06c71d08
    name: Check proxy data
    id: env
    with:
      input: |
        ${{ inputs.env }}
      input-format: ${{ inputs.env-format }}
      filter: ${{ inputs.env-filter || '.' }}
  - uses: envoyproxy/toolshed/gh-actions/jq@dd0c20b6f9fd7edef45a0cd05016eaef06c71d08
    name: Print check proxy data
    with:
      input: ${{ steps.env.outputs.value }}
      options: -C
      print-result: true
  - name: Save environment data
    id: save
    shell: bash
    run: |
      OUTPUT_DIR=$(mktemp -d)
      printf "%s" "$INPUT_ENV"  >> "$OUTPUT_DIR/${{ inputs.name }}.json"
      echo "directory=${OUTPUT_DIR}" >> $GITHUB_OUTPUT
    env:
      INPUT_ENV: ${{ steps.env.outputs.value }}
  - name: Upload environment data
    uses: actions/upload-artifact@v3
    with:
      name: ${{ inputs.name }}
      path: ${{ steps.save.outputs.directory }}
