
inputs:
  url:
    type: string
    required: true
  path:
    type: string

outputs:
  path:
    value: ${{ steps.fetch.outputs.path }}

runs:
  using: "composite"
  steps:
  - run: |
      URL="${URL%"${URL##*[![:space:]]}"}"
      if [[ -n "${{ inputs.path }}" ]]; then
          path="${{ inputs.path }}"
      else
          path=$(mktemp -d)
      fi
      mkdir -p "$path"
      cd "$path"
      curl -sLO "${URL}"
      filepath="$(realpath "$(basename "${URL}")")"
      echo "path=${filepath}" >> $GITHUB_OUTPUT
      cd -
    shell: bash
    id: fetch
    env:
      URL: ${{ inputs.fetch }}
