
inputs:
  resources:
    type: string
    default: |
      github
      runner
      job
      needs
      steps
      step
      env
      vars
  env:
    type: string
  job:
    type: string
  needs:
    type: string
  vars:
    type: string


runs:
  using: composite
  steps:
  - uses: envoyproxy/toolshed/gh-actions/jq@c1f2adfdd7f45e07061db52c669cefb40c75b02e
    name: Config
    id: config
    with:
      input: ${{ inputs.resources }}
      input-format: text
      options: -Rs
      filter: |
        split("\n") | map(select(length > 0))
  - uses: envoyproxy/toolshed/gh-actions/jq@c1f2adfdd7f45e07061db52c669cefb40c75b02e
    name: Print github
    if: ${{ contains(fromJSON(steps.config.outputs.value), 'github') }}
    with:
      input: ${{ toJSON(github) }}
      options: -C
      print-result: true
      use-tmp-file: true
      filter: |
        del(.token)
  - uses: envoyproxy/toolshed/gh-actions/jq@c1f2adfdd7f45e07061db52c669cefb40c75b02e
    name: Print runner
    if: ${{ contains(fromJSON(steps.config.outputs.value), 'runner') }}
    with:
      input: ${{ toJSON(runner) }}
      options: -C
      print-result: true
  - uses: envoyproxy/toolshed/gh-actions/jq@c1f2adfdd7f45e07061db52c669cefb40c75b02e
    name: Print job
    if: ${{ contains(fromJSON(steps.config.outputs.value), 'job') }}
    with:
      input: ${{ inputs.job || toJSON(job) }}
      options: -C
      print-result: true
  - uses: envoyproxy/toolshed/gh-actions/jq@c1f2adfdd7f45e07061db52c669cefb40c75b02e
    name: Print env
    if: ${{ contains(fromJSON(steps.config.outputs.value), 'env') }}
    with:
      input: ${{ inputs.env || toJSON(env) }}
      options: -C
      print-result: true
  - uses: envoyproxy/toolshed/gh-actions/jq@c1f2adfdd7f45e07061db52c669cefb40c75b02e
    name: Print env
    if: ${{ contains(fromJSON(steps.config.outputs.value), 'needs') && inputs.needs }}
    with:
      input: ${{ inputs.needs }}
      options: -C
      print-result: true
  - uses: envoyproxy/toolshed/gh-actions/jq@c1f2adfdd7f45e07061db52c669cefb40c75b02e
    name: Print env
    if: ${{ contains(fromJSON(steps.config.outputs.value), 'vars') && inputs.vars }}
    with:
      input: ${{ inputs.vars }}
      options: -C
      print-result: true
