inputs:
  text:
    type: string
    required: true
  matching:
    type: string
    default: >-
      ^/

outputs:
  command:
    value: ${{ fromJSON(steps.command.outputs.value).name }}
  args:
    value: ${{ fromJSON(steps.command.outputs.value).args }}


runs:
  using: composite
  steps:
  - uses: envoyproxy/toolshed/gh-actions/jq@dd0c20b6f9fd7edef45a0cd05016eaef06c71d08
    name: Parse command from text
    id: command
    with:
      input: ${{ inputs.text }}
      options: -sR
      filter: |
        split("\n")
        | map(select(
            test("${{ inputs.matching }}"))
            | split(" ")
            | {name: (.[0] | ltrimstr("/")),
               args: (.[1:] | join(" ") | gsub("\r"; ""))})
        | first // {}
