
inputs:
  name:
    type: string
    default: env
  run-id:
    type: string
    required: true
  check-name:
    type: string
    default:


outputs:
  data:
    value: ${{ steps.data.outputs.data }}
  output:
    value: ${{ steps.toenv.outputs.value }}


runs:
  using: composite
  steps:
  - uses: envoyproxy/toolshed/gh-actions/github/context@fdd652c14d10afbc4a7acb5486d67622daef3499
    name: Github context
    if: ${{ fromJSON(env.CI_DEBUG || false) || fromJSON(env.RUNNER_DEBUG || false) }}
  - name: Download environment data
    id: download
    uses: envoyproxy/toolshed/gh-actions/github/artifact/download@fdd652c14d10afbc4a7acb5486d67622daef3499
    with:
      name: ${{ inputs.name }}
      path: ${{ runner.temp }}
      run-id: ${{ inputs.run-id }}
  - name: Load data
    id: data
    run: |
      DATA=$(cat ${{ runner.temp }}/${{ inputs.name }}.json)
      printf 'data=%s' "${DATA}" >> $GITHUB_OUTPUT
    shell: bash
  - uses: envoyproxy/toolshed/gh-actions/jq@fdd652c14d10afbc4a7acb5486d67622daef3499
    name: Print env data
    if: ${{ fromJSON(env.CI_DEBUG || false) || fromJSON(env.RUNNER_DEBUG || false) }}
    with:
      input: ${{ steps.data.outputs.value }}
      options: -C
      print-result: true

  - uses: envoyproxy/toolshed/gh-actions/github/env/save@fdd652c14d10afbc4a7acb5486d67622daef3499
    name: Save env
    if: ${{ inputs.check-name }}
    with:
      name: env-proxy
      env-format: yaml
      env: |
        workflow-env: ${{ inputs.run-id }}
        check-name: ${{ inputs.check-name }}
        startup-conclusion: ${{ github.event.workflow_run.conclusion }}
